Use authorization code flow with PKCE when a client secret is specified
OctopusDeploy/OpenIDConnectAuthenticationProviders pull request #67
Opened 2022-03-17 23:03 UTC by N-lson

2022-03-30 02:36 UTC, N-lson commented on source/Server.OpenIDConnect.Common/Infrastructure/Pkce.cs
> +    public static class Pkce
There doesn't seem to be a good library that exists for generating these. I've included an excerpt from the original RFC and following their recommendation for creating the code verifier.

2022-04-08 06:35 UTC, zentron requested changes
Couple little requests around code cleanup and a rename of the `SessionId` to `RequestId` but otherwise its looking pretty good.

2022-04-08 06:35 UTC, zentron commented on source/Client.OpenIDConnect/Configuration/OpenIDConnectConfigurationWithClientSecretResource.cs
> -    public class OpenIDConnectConfigurationWithClientSecretResource : OpenIDConnectConfigurationResource
Interested to know the background for this one. Was there nothing that was NOT using the Client Secret?

2022-04-08 06:35 UTC, zentron commented on source/Server.OctopusID/Configuration/OctopusIDConfigureCommands.cs
> -            yield return new ConfigureCommandOption($"{ConfigurationSettingsName}ClientSecret=", "Tell Octopus the shared secret to use for Octopus ID authentication requests.", v =>
Does this mean the old flow with ClientSecret isn't supported at all?

2022-04-08 06:35 UTC, zentron commented on source/Server.OctopusID/Configuration/OctopusIDConfigureCommands.cs
> -            yield return new ConfigureCommandOption($"{ConfigurationSettingsName}ClientSecret=", "Tell Octopus the shared secret to use for Octopus ID authentication requests.", v =>
nvm, I can see it was moved to the base class

2022-04-08 06:35 UTC, zentron commented on source/Server.OpenIDConnect.Common/Web/LoginStateWithSessionId.cs
> +            SessionId = sessionId;
Im thinking this is more a `RequestId` right? Might be more accurate

2022-04-08 06:35 UTC, zentron commented on source/Server.OpenIDConnect.Common/Web/UserAuthenticatedPkceAction.cs
> +            var request = new HttpRequestMessage(HttpMethod.Post, issuerConfig.TokenEndpoint);
Bit of a tidy up here. 
Lets wrap the blob cleanup\retrieval logic and the response creation logic into their own methods to keep this method reading cleanly

2022-04-08 06:35 UTC, zentron commented on source/Server.OpenIDConnect.Common/Web/UserAuthenticatedPkceAction.cs
> +            // Step 1: Try and get all of the details from the request making sure there are no errors passed back from the external identity provider
Im guessing this is a bit of C+P from what was in the original `UserAuthenticatedAction` method. is there anything here that we have in common that can be extracted out?

2022-04-08 06:35 UTC, zentron commented on source/Server.OpenIDConnect.Common/Web/UserAuthenticatedPkceAction.cs
> +        IResultFromExtension<IUser> GetOrCreateUser(UserResource userResource, string[] groups, CancellationToken cancellationToken)
Again, is there much in here which is really different from the existing class?

2022-04-08 06:36 UTC, zentron commented on source/Server.OpenIDConnect.Common/Infrastructure/Pkce.cs
> +    public static class Pkce
All good, it does looks simple enough so I think what youve gone with is A-OK

2022-04-10 23:31 UTC, N-lson commented on source/Client.OpenIDConnect/Configuration/OpenIDConnectConfigurationWithClientSecretResource.cs
> -    public class OpenIDConnectConfigurationWithClientSecretResource : OpenIDConnectConfigurationResource
Octopus ID was the only one using the client secret. All the other providers weren't using it. Since now all the providers will use the client secret there isn't a need to keep multiple classes for the purpose of separating it out.

2022-04-14 02:29 UTC, N-lson commented on source/Server.OpenIDConnect.Common/Web/AuthServerResponseHandler.cs
> +    public class AuthServerResponseHandler<TAuthTokenHandler> where TAuthTokenHandler : IAuthTokenHandler
Technically this either handles a request (in the case of the implicit flow) or a response (in the case of auth code flow) from the auth server but I went with naming it `ResponseHandler`.

2022-04-14 02:29 UTC, N-lson commented on source/Server.OpenIDConnect.Common/Web/AuthServerResponseHandler.cs
> +            var principalContainer = await authTokenHandler.GetPrincipalAsync(requestForm, out _);
No longer use the out var for the state - could also remove it from the method itself?

2022-04-14 02:29 UTC, N-lson commented on source/Server.OpenIDConnect.Common/Web/AuthServerResponseHandler.cs
> +                .WithCookie(new OctoCookie(UserAuthConstants.OctopusNonceCookieName, Guid.NewGuid().ToString()) {HttpOnly = true, Secure = false, Expires = DateTimeOffset.MinValue});
I'm guessing setting these cookies just resets them to some value so they can't be re-used?

2022-04-14 02:29 UTC, N-lson commented on source/Server.OpenIDConnect.Common/Web/UserAuthenticatedAction.cs
> -            // Step 1: Try and get all of the details from the request making sure there are no errors passed back from the external identity provider
I removed all the comments. I think some of the method names are very clear, others maybe it would be useful to keep the comment?

2022-04-14 02:32 UTC, N-lson commented on source/Server.OpenIDConnect.Common/Web/UserAuthenticationAction.cs
> +                new CancellationToken());
Is `new CancellationToken` ok here?

2022-04-20 05:43 UTC, zentron approved these changes
Minor comment around the cancellation token but once that is fixed and this all still works then feel free to merge :) 
Thanks for the additional time spent 👍

2022-04-20 05:43 UTC, zentron commented on source/Server.OpenIDConnect.Common/Web/UserAuthenticationAction.cs
> +                new CancellationToken());
I cant see many places where we might already have a token so could you perhaps just wrap the code as high as it makes sense with a 
```
   using var cts = new CancellationTokenSource(TimeSpan.FromMinutes(1));
```
and pass it around where necessary

2022-04-20 22:55 UTC, merged